"""remove_unused_langfuse_fields

Revision ID: 7aa32ba8f629
Revises: ec8e1149869c
Create Date: 2026-06-28 22:05:45.213017

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7aa32ba8f629'
down_revision: Union[str, None] = 'ec8e1149869c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('agent_runs', 'langfuse_trace_id')
    op.drop_column('agent_runs', 'langfuse_trace_url')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('agent_runs', sa.Column('langfuse_trace_url', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('agent_runs', sa.Column('langfuse_trace_id', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
