"""remove_system_role_from_chat_messages

Revision ID: 995be2700764
Revises: c4f9b7a12e3d
Create Date: 2026-06-21 17:10:59.481730

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import context, op

# revision identifiers, used by Alembic.
revision: str = "995be2700764"
down_revision: str | None = "c4f9b7a12e3d"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def _drop_constraint_if_exists(table_name: str, constraint_name: str, constraint_type: str) -> None:
    if context.is_offline_mode():
        op.execute(f"ALTER TABLE {table_name} DROP CONSTRAINT IF EXISTS {constraint_name}")
        return

    bind = op.get_bind()
    inspector = sa.inspect(bind)
    if constraint_type == "foreignkey":
        constraint_names = {
            constraint["name"] for constraint in inspector.get_foreign_keys(table_name)
        }
    else:
        constraint_names = {
            constraint["name"] for constraint in inspector.get_check_constraints(table_name)
        }

    if constraint_name in constraint_names:
        op.drop_constraint(constraint_name, table_name, type_=constraint_type)


def _foreign_key_exists(table_name: str, constraint_name: str) -> bool:
    bind = op.get_bind()
    inspector = sa.inspect(bind)
    return constraint_name in {
        constraint["name"] for constraint in inspector.get_foreign_keys(table_name)
    }


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    _drop_constraint_if_exists("audit_logs", "audit_logs_session_id_fkey", "foreignkey")
    _drop_constraint_if_exists("audit_logs", "audit_logs_run_id_fkey", "foreignkey")

    # Drop old check constraint and create new one
    _drop_constraint_if_exists("chat_messages", "ck_chat_messages_role", "check")
    op.create_check_constraint(
        "ck_chat_messages_role",
        "chat_messages",
        "role IN ('user', 'assistant', 'tool')",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Drop new check constraint and restore old one
    _drop_constraint_if_exists("chat_messages", "ck_chat_messages_role", "check")
    op.create_check_constraint(
        "ck_chat_messages_role",
        "chat_messages",
        "role IN ('user', 'assistant', 'system', 'tool')",
    )

    if context.is_offline_mode() or not _foreign_key_exists("audit_logs", "audit_logs_run_id_fkey"):
        op.create_foreign_key(
            op.f("audit_logs_run_id_fkey"),
            "audit_logs",
            "agent_runs",
            ["run_id"],
            ["id"],
            ondelete="SET NULL",
        )
    if context.is_offline_mode() or not _foreign_key_exists(
        "audit_logs", "audit_logs_session_id_fkey"
    ):
        op.create_foreign_key(
            op.f("audit_logs_session_id_fkey"),
            "audit_logs",
            "sessions",
            ["session_id"],
            ["id"],
            ondelete="SET NULL",
        )
    # ### end Alembic commands ###
