"""remove_skill_version_and_session_status

Revision ID: c2eb5156b73c
Revises: 3f4a5b6c7d8e
Create Date: 2026-07-05 01:47:12.057425

"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "c2eb5156b73c"
down_revision: str | None = "3f4a5b6c7d8e"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sessions', 'status')
    op.drop_column('skills', 'version')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "skills",
        sa.Column(
            "version",
            sa.VARCHAR(length=30),
            server_default=sa.text("'1.0.0'::character varying"),
            autoincrement=False,
            nullable=False,
        ),
    )
    op.add_column(
        "sessions",
        sa.Column(
            "status",
            sa.VARCHAR(length=30),
            server_default=sa.text("'active'::character varying"),
            autoincrement=False,
            nullable=False,
        ),
    )
    # ### end Alembic commands ###
