"""remove_unused_tool_call_fields

Revision ID: ec8e1149869c
Revises: b8d4f1c2a9e7
Create Date: 2026-06-28 21:39:10.143208

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ec8e1149869c'
down_revision: Union[str, None] = 'b8d4f1c2a9e7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('ck_tool_calls_skill_source', 'tool_calls', type_='check')
    op.drop_index(op.f('idx_tool_calls_skill'), table_name='tool_calls')
    op.create_index('idx_tool_calls_skill_name', 'tool_calls', ['skill_name'], unique=False)
    op.drop_column('tool_calls', 'skill_source')
    op.drop_column('tool_calls', 'skill_version')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tool_calls', sa.Column('skill_version', sa.VARCHAR(length=30), server_default=sa.text("'1.0.0'::character varying"), autoincrement=False, nullable=False))
    op.add_column('tool_calls', sa.Column('skill_source', sa.VARCHAR(length=20), server_default=sa.text("'internal'::character varying"), autoincrement=False, nullable=False))
    op.drop_index('idx_tool_calls_skill_name', table_name='tool_calls')
    op.create_index(op.f('idx_tool_calls_skill'), 'tool_calls', ['skill_name', 'skill_source'], unique=False)
    op.create_check_constraint(
        'ck_tool_calls_skill_source',
        'tool_calls',
        "skill_source IN ('internal', 'mcp')"
    )
    # ### end Alembic commands ###
